apiVersion: apps/v1
kind: Deployment
metadata:
  name: andsouzam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vittae
  template:
    metadata:
      labels:
        app: vittae
    spec:
      containers:
      - name: andsouzam
        image: vittae
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        